#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DB_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BUNDLES_DIR="$DB_DIR/bundles"
GUARD_SCRIPT="$SCRIPT_DIR/guard_no_duplicate_procs.sh"
RUNTIME_GUARD_SCRIPT="$SCRIPT_DIR/guard_runtime_proc_contract.sh"

BASE_SCHEMA_SOURCE="$DB_DIR/schema/BASE_SCHEMA.sql"
PROCEDURES_SOURCE="$SCRIPT_DIR/procedures/CANONICAL_STORED_PROCEDURES.sql"

MIGRATION_FILES=(
  "migrations/V202602190900__add_views_and_location_to_posts.sql"
  "migrations/V202602190905__add_phone_to_users.sql"
  "migrations/V202602190907__add_user_profile_fields.sql"
  "migrations/V202602190910__drop_username_from_users.sql"
  "migrations/V202602190915__add_category_visual_fields.sql"
  "migrations/V202602190920__add_favorites_table.sql"
  "migrations/V202602190925__fix_post_image_url_size.sql"
  "migrations/V202602190930__add_chat_review_tables_and_indexes.sql"
  "migrations/V202602190935__enhance_database_performance_and_integrity.sql"
  "migrations/V202602190940__add_schema_versioning_and_search_indexes.sql"
  "migrations/V202602190945__normalize_status_lookups_and_index_cleanup.sql"
  "migrations/V202602191000__standardize_utc_default_constraints.sql"
  "migrations/V202602191010__enforce_user_status_constraint.sql"
  "migrations/V202602191020__add_normalized_search_columns_and_indexes.sql"
)

SEED_BASELINE_FILES=(
  "seeds/baseline/BASELINE_REFERENCE_DATA.sql"
)

SEED_DEV_FILES=(
  "seeds/dev/FIX_DEFAULT_USER_CREDENTIALS.sql"
  "seeds/dev/INSERT_SAMPLE_POSTS.sql"
  "seeds/dev/INSERT_DUMMY_IMAGES.sql"
)

SEED_TEST_FILES=(
  "seeds/test/CREATE_TEST_USER.sql"
)

write_header() {
  local destination="$1"
  local title="$2"

  cat > "$destination" <<EOT
-- =============================================================================
-- ${title}
-- Auto-generated by database/scripts/build_sql_bundles.sh.
-- Do not edit this file directly; edit source SQL and rerun the builder.
-- =============================================================================

EOT
}

append_source_sql() {
  local destination="$1"
  local source_path="$2"
  local relative_source="${source_path#"$SCRIPT_DIR"/}"

  if [[ "$relative_source" == "$source_path" ]]; then
    relative_source="${source_path#"$DB_DIR"/}"
  fi

  cat >> "$destination" <<EOT
-- -----------------------------------------------------------------------------
-- Source: ${relative_source}
-- -----------------------------------------------------------------------------

EOT

  cat "$source_path" >> "$destination"
  printf "\n\n" >> "$destination"
}

validate_sources() {
  if [[ ! -f "$BASE_SCHEMA_SOURCE" ]]; then
    echo "Missing base schema source: $BASE_SCHEMA_SOURCE" >&2
    exit 1
  fi

  if [[ ! -f "$PROCEDURES_SOURCE" ]]; then
    echo "Missing procedures source: $PROCEDURES_SOURCE" >&2
    exit 1
  fi

  if [[ ! -x "$GUARD_SCRIPT" ]]; then
    echo "Missing or non-executable guard script: $GUARD_SCRIPT" >&2
    exit 1
  fi

  if [[ ! -x "$RUNTIME_GUARD_SCRIPT" ]]; then
    echo "Missing or non-executable runtime contract guard script: $RUNTIME_GUARD_SCRIPT" >&2
    exit 1
  fi

  local file=""
  for file in \
    "${MIGRATION_FILES[@]}" \
    "${SEED_BASELINE_FILES[@]}" \
    "${SEED_DEV_FILES[@]}" \
    "${SEED_TEST_FILES[@]}"; do
    if [[ ! -f "$SCRIPT_DIR/$file" ]]; then
      echo "Missing SQL source: $SCRIPT_DIR/$file" >&2
      exit 1
    fi
  done
}

build_schema_bundle() {
  local destination="$BUNDLES_DIR/schema.sql"
  write_header "$destination" "Schema Bundle"
  append_source_sql "$destination" "$BASE_SCHEMA_SOURCE"
}

build_migrations_bundle() {
  local destination="$BUNDLES_DIR/migrations.sql"
  write_header "$destination" "Migrations Bundle"

  local file=""
  for file in "${MIGRATION_FILES[@]}"; do
    append_source_sql "$destination" "$SCRIPT_DIR/$file"
  done
}

build_procedures_bundle() {
  local destination="$BUNDLES_DIR/procedures.sql"
  write_header "$destination" "Stored Procedures Bundle"
  append_source_sql "$destination" "$PROCEDURES_SOURCE"
}

append_seed_group() {
  local destination="$1"
  local group_title="$2"
  shift 2

  cat >> "$destination" <<EOT
-- =============================================================================
-- ${group_title}
-- =============================================================================

EOT

  local file=""
  for file in "$@"; do
    append_source_sql "$destination" "$SCRIPT_DIR/$file"
  done
}

build_seed_bundle() {
  local destination="$BUNDLES_DIR/seed_data.sql"
  write_header "$destination" "Seed Data Bundle (Baseline)"

  append_seed_group "$destination" "Baseline Seeds" "${SEED_BASELINE_FILES[@]}"
}

build_seed_dev_bundle() {
  local destination="$BUNDLES_DIR/seed_dev.sql"
  write_header "$destination" "Seed Data Bundle (Development)"

  append_seed_group "$destination" "Development Seeds" "${SEED_DEV_FILES[@]}"
}

build_seed_test_bundle() {
  local destination="$BUNDLES_DIR/seed_test.sql"
  write_header "$destination" "Seed Data Bundle (Test)"

  append_seed_group "$destination" "Test Seeds" "${SEED_TEST_FILES[@]}"
}

build_master_bundle() {
  local destination="$BUNDLES_DIR/master.sql"
  write_header "$destination" "Master Deployment Bundle (Base Schema + Migrations + Procedures)"

  append_source_sql "$destination" "$BASE_SCHEMA_SOURCE"

  local file=""
  for file in "${MIGRATION_FILES[@]}"; do
    append_source_sql "$destination" "$SCRIPT_DIR/$file"
  done

  append_source_sql "$destination" "$PROCEDURES_SOURCE"
}

main() {
  mkdir -p "$BUNDLES_DIR"
  validate_sources
  "$GUARD_SCRIPT"
  "$RUNTIME_GUARD_SCRIPT"

  rm -f "$BUNDLES_DIR/seed.sql" "$BUNDLES_DIR/views.sql" \
    "$BUNDLES_DIR/indexes.sql" "$BUNDLES_DIR/seed_dev.sql" "$BUNDLES_DIR/seed_test.sql"

  build_schema_bundle
  build_migrations_bundle
  build_procedures_bundle
  build_seed_bundle
  build_seed_dev_bundle
  build_seed_test_bundle
  build_master_bundle

  echo "SQL bundles generated:"
  echo "  $BUNDLES_DIR/schema.sql"
  echo "  $BUNDLES_DIR/migrations.sql"
  echo "  $BUNDLES_DIR/procedures.sql"
  echo "  $BUNDLES_DIR/seed_data.sql"
  echo "  $BUNDLES_DIR/seed_dev.sql"
  echo "  $BUNDLES_DIR/seed_test.sql"
  echo "  $BUNDLES_DIR/master.sql"
}

main "$@"
