#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DB_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BUNDLES_DIR="$DB_DIR/bundles"
GUARD_SCRIPT="$SCRIPT_DIR/guard_no_duplicate_procs.sh"
RUNTIME_GUARD_SCRIPT="$SCRIPT_DIR/guard_runtime_proc_contract.sh"
ATOMICITY_GUARD_SCRIPT="$SCRIPT_DIR/guard_migration_atomicity.sh"
CHECKSUM_GUARD_SCRIPT="$SCRIPT_DIR/guard_migration_checksums.sh"

BASE_SCHEMA_SOURCE="$DB_DIR/schema/BASE_SCHEMA.sql"

MIGRATION_FILES=()

SEED_BASELINE_FILES=(
  "seeds/baseline/BASELINE_REFERENCE_DATA.sql"
  "seeds/baseline/BASELINE_LOCATIONS.sql"
)

SEED_DEV_FILES=(
  "seeds/dev/INSERT_DEV_SEED_USER.sql"
  "seeds/dev/INSERT_SAMPLE_POSTS.sql"
  "seeds/dev/INSERT_DUMMY_IMAGES.sql"
)

SEED_TEST_FILES=(
  "seeds/test/CREATE_TEST_USER.sql"
)

write_header() {
  local destination="$1"
  local title="$2"

  cat > "$destination" <<EOT
-- =============================================================================
-- ${title}
-- Auto-generated by database/scripts/build_sql_bundles.sh.
-- Do not edit this file directly; edit source SQL and rerun the builder.
-- =============================================================================

EOT
}

append_source_sql() {
  local destination="$1"
  local source_path="$2"
  local relative_source="${source_path#"$SCRIPT_DIR"/}"

  if [[ "$relative_source" == "$source_path" ]]; then
    relative_source="${source_path#"$DB_DIR"/}"
  fi

  cat >> "$destination" <<EOT
-- -----------------------------------------------------------------------------
-- Source: ${relative_source}
-- -----------------------------------------------------------------------------

EOT

  cat "$source_path" >> "$destination"
  printf "\n\n" >> "$destination"
}

collect_migration_files() {
  local migration_dir="$SCRIPT_DIR/migrations"
  local -a canonical_files=()
  local relative=""

  if [[ -d "$migration_dir" ]]; then
    while IFS= read -r file; do
      relative="${file#"$SCRIPT_DIR"/}"
      canonical_files+=("$relative")
    done < <(find "$migration_dir" -maxdepth 1 -type f -name 'V*.sql' | sort)
  fi

  if [[ ${#canonical_files[@]} -gt 0 ]]; then
    MIGRATION_FILES=("${canonical_files[@]}")
    return
  fi

  echo "Missing active canonical migrations under $migration_dir (expected top-level V*.sql files)." >&2
  echo "Legacy migrations under $DB_DIR/archive/migrations-legacy are intentionally excluded from bundles." >&2
  exit 1
}

enforce_runtime_tree_boundaries() {
  local -a stale_runtime_sources=()
  local file=""

  while IFS= read -r file; do
    stale_runtime_sources+=("$file")
  done < <(find "$SCRIPT_DIR/bundles" "$SCRIPT_DIR/archive" -type f -name '*.sql' 2>/dev/null | sort)

  if [[ ${#stale_runtime_sources[@]} -eq 0 ]]; then
    return
  fi

  echo "Error: stale SQL sources were found under runtime-adjacent paths." >&2
  echo "Move historical SQL to apps/api/database/archive/* and keep generated output in apps/api/database/bundles/* only." >&2
  echo "Offending files:" >&2
  for file in "${stale_runtime_sources[@]}"; do
    echo "  - ${file#"$DB_DIR"/}" >&2
  done
  exit 1
}

validate_sources() {
  if [[ ! -f "$BASE_SCHEMA_SOURCE" ]]; then
    echo "Missing base schema source: $BASE_SCHEMA_SOURCE" >&2
    exit 1
  fi

  if [[ ! -x "$GUARD_SCRIPT" ]]; then
    echo "Missing or non-executable guard script: $GUARD_SCRIPT" >&2
    exit 1
  fi

  if [[ ! -x "$RUNTIME_GUARD_SCRIPT" ]]; then
    echo "Missing or non-executable runtime contract guard script: $RUNTIME_GUARD_SCRIPT" >&2
    exit 1
  fi

  if [[ ! -x "$ATOMICITY_GUARD_SCRIPT" ]]; then
    echo "Missing or non-executable migration atomicity guard script: $ATOMICITY_GUARD_SCRIPT" >&2
    exit 1
  fi

  if [[ ! -x "$CHECKSUM_GUARD_SCRIPT" ]]; then
    echo "Missing or non-executable migration checksum guard script: $CHECKSUM_GUARD_SCRIPT" >&2
    exit 1
  fi

  local file=""
  for file in \
    "${MIGRATION_FILES[@]}" \
    "${SEED_BASELINE_FILES[@]}" \
    "${SEED_DEV_FILES[@]}" \
    "${SEED_TEST_FILES[@]}"; do
    if [[ ! -f "$SCRIPT_DIR/$file" ]]; then
      echo "Missing SQL source: $SCRIPT_DIR/$file" >&2
      exit 1
    fi
  done
}

build_schema_bundle() {
  local destination="$BUNDLES_DIR/schema.sql"
  write_header "$destination" "Schema Bundle"
  append_source_sql "$destination" "$BASE_SCHEMA_SOURCE"
}

build_migrations_bundle() {
  local destination="$BUNDLES_DIR/migrations.sql"
  write_header "$destination" "Migrations Bundle"

  local file=""
  for file in "${MIGRATION_FILES[@]}"; do
    append_source_sql "$destination" "$SCRIPT_DIR/$file"
  done
}

append_seed_group() {
  local destination="$1"
  local group_title="$2"
  shift 2

  cat >> "$destination" <<EOT
-- =============================================================================
-- ${group_title}
-- =============================================================================

EOT

  local file=""
  for file in "$@"; do
    append_source_sql "$destination" "$SCRIPT_DIR/$file"
  done
}

build_seed_bundle() {
  local destination="$BUNDLES_DIR/seed_data.sql"
  write_header "$destination" "Seed Data Bundle (Baseline)"

  append_seed_group "$destination" "Baseline Seeds" "${SEED_BASELINE_FILES[@]}"
}

build_seed_dev_bundle() {
  local destination="$BUNDLES_DIR/seed_dev.sql"
  write_header "$destination" "Seed Data Bundle (Development)"

  append_seed_group "$destination" "Development Seeds" "${SEED_DEV_FILES[@]}"
}

build_seed_test_bundle() {
  local destination="$BUNDLES_DIR/seed_test.sql"
  write_header "$destination" "Seed Data Bundle (Test)"

  append_seed_group "$destination" "Test Seeds" "${SEED_TEST_FILES[@]}"
}

build_master_bundle() {
  local destination="$BUNDLES_DIR/master.sql"
  write_header "$destination" "Master Deployment Bundle (Base Schema + Migrations)"

  append_source_sql "$destination" "$BASE_SCHEMA_SOURCE"

  local file=""
  for file in "${MIGRATION_FILES[@]}"; do
    append_source_sql "$destination" "$SCRIPT_DIR/$file"
  done
}

main() {
  mkdir -p "$BUNDLES_DIR"
  enforce_runtime_tree_boundaries
  collect_migration_files
  validate_sources
  "$GUARD_SCRIPT"
  "$RUNTIME_GUARD_SCRIPT"
  "$CHECKSUM_GUARD_SCRIPT"
  "$ATOMICITY_GUARD_SCRIPT"

  rm -f "$BUNDLES_DIR/seed.sql" "$BUNDLES_DIR/views.sql" \
    "$BUNDLES_DIR/indexes.sql" "$BUNDLES_DIR/procedures.sql" \
    "$BUNDLES_DIR/seed_dev.sql" "$BUNDLES_DIR/seed_test.sql"

  build_schema_bundle
  build_migrations_bundle
  build_seed_bundle
  build_seed_dev_bundle
  build_seed_test_bundle
  build_master_bundle

  echo "SQL bundles generated:"
  echo "  $BUNDLES_DIR/schema.sql"
  echo "  $BUNDLES_DIR/migrations.sql"
  echo "  $BUNDLES_DIR/seed_data.sql"
  echo "  $BUNDLES_DIR/seed_dev.sql"
  echo "  $BUNDLES_DIR/seed_test.sql"
  echo "  $BUNDLES_DIR/master.sql"
}

main "$@"
