SET XACT_ABORT ON;
BEGIN TRY
    BEGIN TRANSACTION;

    ALTER TABLE [dbo].[Cities] ADD [CityNameAr] NVARCHAR(100) NOT NULL DEFAULT N'';
    ALTER TABLE [dbo].[Areas] ADD [AreaNameAr] NVARCHAR(100) NOT NULL DEFAULT N'';

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH
GO
