SET XACT_ABORT ON;
BEGIN TRY
    BEGIN TRANSACTION;

    GRANT INSERT, UPDATE, DELETE ON dbo.Cities TO tijarahjo_app_role;
    GRANT INSERT, UPDATE, DELETE ON dbo.Areas TO tijarahjo_app_role;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH
GO
