SET XACT_ABORT ON;
GO

BEGIN TRY
    BEGIN TRANSACTION;

    IF COL_LENGTH(N'dbo.Cities', N'CityNameAr') IS NULL
    BEGIN
        ALTER TABLE [dbo].[Cities] ADD [CityNameAr] NVARCHAR(100) NOT NULL CONSTRAINT DF_Cities_CityNameAr DEFAULT N'';
    END

    IF COL_LENGTH(N'dbo.Areas', N'AreaNameAr') IS NULL
    BEGIN
        ALTER TABLE [dbo].[Areas] ADD [AreaNameAr] NVARCHAR(100) NOT NULL CONSTRAINT DF_Areas_AreaNameAr DEFAULT N'';
    END

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH
GO
